### ISSUE TITLE
Navbar icons wrong position

### ISSUE THREAD

**Issue by kristianvld** [ItemizeNTNU/website#20]
The login, logout and profile page icons are incorrectly positioned in the navbar on mobile.

They should be positioned on the right next to the hamburger menu, or inside it.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/7207116/135563269-128a15ee-c8e9-4301-a53d-790f5b14238a.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/7207116/135563310-5602f173-bff8-4c87-8ba8-31730701bc6f.png">

**Comment by iampk94** [comment]
@kristianvld can i work on this?
