### ISSUE TITLE
Synchronize calendar events with the new discord events

### ISSUE THREAD

**Issue by kristianvld** [ItemizeNTNU/website#30]
Discord had added a new scheduled event support to servers:
https://support.discord.com/hc/en-us/articles/4409494125719-Scheduled-Events

Events should be synchronized when events are edited from the events admin page. API docs:
https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event

**Comment by calidbaba** [comment]
I can take a look at this one

**Comment by kristianvld** [comment]
Fixed in #45
